openapi: '3.0.2'
info:
  title: Windows Virtual Machines Control
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /test:
    get:
      responses:
        '200':
          description: OK